const remove = async () => {};

try {
  await remove();
} catch (err) {
  throw err;
}
